"""Generate the Products section from data/ YAML.

    python scripts/build_products.py

Reads  data/portfolio/{themes.yml,products/*.yml}   (extracted from the portfolio PDF)
       data/extra/{themes.yml,products/*.yml}       (hand-authored, not in portfolio)
       data/guides.yml                              (user guides hosted on this site)
Writes docs/products/**                             (generated: do not edit by hand)
       the nav block between the GENERATED markers in mkdocs.yml
"""
from __future__ import annotations

import html
import pathlib
import re
import shutil

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "docs" / "products"
CONFIG = ROOT / "mkdocs.yml"

e = html.escape


def load(folder: str):
    themes = yaml.safe_load((DATA / folder / "themes.yml").read_text()) or []
    products = {}
    for f in sorted((DATA / folder / "products").glob("*.yml")):
        p = yaml.safe_load(f.read_text())
        products[p["slug"]] = p
    return themes, products


def ul(items) -> str:
    if not items:
        return ""
    if isinstance(items, str):
        return f"<p>{e(items)}</p>"
    out = ["<ul>"]
    for it in items:
        out.append(f"<li>{e(it['text'])}")
        if it.get("sub"):
            out.append('<ul class="bgs-sub">' + "".join(f"<li>{e(s)}</li>" for s in it["sub"]) + "</ul>")
        out.append("</li>")
    out.append("</ul>")
    return "".join(out)


def section(title: str, body: str, anchor: str) -> str:
    if not body:
        return ""
    return f'<section class="bgs-section" id="{anchor}"><h2>{e(title)}</h2>{body}</section>\n'


def licencing(blocks, links) -> str:
    out = []
    for b in blocks or []:
        text = e(b.get("text") or "")
        if links.get("enquiry"):
            text = text.replace("get in touch", f'<a href="{e(links["enquiry"])}">get in touch</a>', 1)
        if links.get("resellers"):
            text = text.replace("full list of BGS re-sellers",
                                f'<a href="{e(links["resellers"])}">full list of BGS re-sellers</a>', 1)
        if b.get("heading"):
            out.append(f'<p class="bgs-panel-sub">{e(b["heading"])}</p>')
        if text:
            out.append(f"<p>{text}</p>")
    return "".join(out)


def open_badge(p) -> str:
    return '<span class="bgs-badge">Open data</span>' if p.get("licence") == "OGL" else ""


def desc(p) -> str:
    o = p.get("overview") or ""
    o = o if isinstance(o, str) else " ".join(i["text"] for i in o)
    return o[:155].replace('"', "'")


def rel(from_depth: int, target: str) -> str:
    return "../" * from_depth + target


def product_page(p, theme, guide_slug, guides) -> str:
    links = p.get("links") or {}
    depth = 3  # docs/products/<theme>/<slug>/index.md -> site root is ../../../ (directory URLs)
    img = f'<img src="{rel(depth, p["image"])}" alt="Example of {e(p["name"])} data">' if p.get("image") else ""
    further = []
    if links.get("web_page"):
        further.append(f'<a href="{e(links["web_page"])}">&gt; Web page</a>')
    if guide_slug:
        further.append(f'<a href="{"user-guide/" if guide_slug == p["slug"] else "../" + guide_slug + "/user-guide/"}">&gt; User guide</a>')
    elif links.get("user_guide_source"):
        further.append(f'<a href="{e(links["user_guide_source"])}">&gt; User guide (bgs.ac.uk)</a>')
    if links.get("doi"):
        further.append(f'<a href="{e(links["doi"])}">&gt; Dataset DOI</a>')
    badge = ""
    if p.get("licence") == "OGL":
        badge = '<span class="bgs-badge">Open data</span>'
    pages = p.get("portfolio_pages")
    source = (f'<p class="bgs-source">Source: BGS Product Portfolio 2026–2027, pp. {pages[0]}–{pages[-1]}.</p>'
              if pages else "")
    enquiry = links.get("enquiry")
    contact = (f'<div class="bgs-panel bgs-contact"><h2>Contact</h2>'
               f'<p><a href="{e(enquiry)}">Make an enquiry</a> about licencing this data.</p></div>') if enquiry else ""
    return f"""---
title: "{p['name']}"
description: "{desc(p)}"
hide:
  - toc
---

<!-- GENERATED by scripts/build_products.py from data/. Edit the YAML, not this file. -->

<div class="bgs-hero"><p class="bgs-kicker">Product portfolio</p><h1>{e(p['name'])}{badge}</h1></div>

<div class="bgs-product">
<div class="bgs-main">
{section("Overview", ul(p.get("overview")), "overview")}
{section("Product benefits", ul(p.get("benefits")), "benefits")}
{section("Key features", ul(p.get("features")), "features")}
{section("Target markets", ul(p.get("target_markets")), "target-markets")}
{section("Challenges faced by customers", ul(p.get("challenges")), "challenges")}
{section("Use cases", ul(p.get("use_cases")), "use-cases")}
{contact}
{source}
</div>
<aside class="bgs-side">
{img}
<div class="bgs-panel bgs-licencing"><h2>Licencing</h2>{licencing(p.get("licencing"), links)}</div>
<div class="bgs-further"><h2>Further information</h2>{"".join(further)}</div>
</aside>
</div>
"""


def guide_page(p, g) -> str:
    pdf = "../../../../" + g["file"]
    doi = f' · <a href="{e(g["doi"])}">DOI</a>' if g.get("doi") else ""
    return f"""---
title: "{p['name']} – user guide"
hide:
  - toc
---

<!-- GENERATED by scripts/build_products.py -->

<div class="bgs-hero"><p class="bgs-kicker">User guide · {e(g['report'])}</p><h1>{e(p['name'])}</h1></div>

<p class="bgs-guide-meta">{e(g['title'])} ({g['year']}). British Geological Survey Open Report {e(g['report'])}.{doi}
<a class="md-button md-button--primary" href="{pdf}" download>Download PDF</a></p>

<object class="bgs-pdf" data="{pdf}#view=FitH" type="application/pdf" aria-label="{e(g['title'])}">
  <p>Your browser can't display the PDF inline. <a href="{pdf}">Open the user guide (PDF)</a>.</p>
</object>
"""


def theme_page(t, products) -> str:
    items = []
    for slug in t["products"]:
        p = products[slug]
        tag = t.get("taglines", {}).get(slug) or ""
        items.append(f'<li><a href="{slug}/">{e(p["name"])}</a>{open_badge(p)} {e(tag)}</li>')
    cards = []
    for slug in t["products"]:
        p = products[slug]
        img = f'<img src="../../{p["image"]}" alt="" loading="lazy">' if p.get("image") else '<div class="bgs-card-noimg"></div>'
        cards.append(f'<a class="bgs-card" href="{slug}/">{img}<span>{e(p["name"])}{open_badge(p)}</span></a>')
    return f"""---
title: "{t['title']}"
hide:
  - toc
---

<!-- GENERATED by scripts/build_products.py -->

<div class="bgs-divider">
  <div class="bgs-divider-art"><div class="bgs-divider-circle"><img src="../../assets/brand/circle-{t['slug'] if t.get('in_portfolio', True) else 'cover'}.webp" alt=""></div><h1>{e(t['title'])}</h1></div>
  <div class="bgs-divider-text">
    <p>{e(t.get('intro', ''))}</p>
    <p>These datasets include:</p>
    <ul class="bgs-divider-list">{''.join(items)}</ul>
  </div>
</div>

<div class="bgs-cards">{''.join(cards)}</div>
"""


def main():
    pthemes, products = load("portfolio")
    xthemes, xproducts = load("extra")
    products.update(xproducts)
    themes = pthemes + xthemes
    guides = yaml.safe_load((DATA / "guides.yml").read_text()) or {}
    guide_for = {}
    for gslug, g in guides.items():
        guide_for[gslug] = gslug
        for s in g.get("covers", []):
            guide_for[s] = gslug

    if OUT.exists():
        shutil.rmtree(OUT)
    nav = []
    for t in themes:
        tdir = OUT / t["slug"]
        tdir.mkdir(parents=True)
        (tdir / "index.md").write_text(theme_page(t, products))
        tnav = [f"products/{t['slug']}/index.md"]
        for slug in t["products"]:
            p = products[slug]
            pdir = tdir / slug
            pdir.mkdir()
            gs = guide_for.get(slug)
            (pdir / "index.md").write_text(product_page(p, t, gs, guides))
            if gs == slug:
                # every page is an index.md so file-relative == URL-relative links,
                # which keeps raw-HTML paths identical under Zensical and MkDocs
                (pdir / "user-guide").mkdir()
                (pdir / "user-guide" / "index.md").write_text(guide_page(p, guides[slug]))
                tnav.append({p["name"]: [f"products/{t['slug']}/{slug}/index.md",
                                         {"User guide": f"products/{t['slug']}/{slug}/user-guide/index.md"}]})
            else:
                tnav.append({p["name"]: f"products/{t['slug']}/{slug}/index.md"})
        nav.append({t["title"]: tnav})

    # products landing page (the portfolio's cover + contents)
    rows = []
    for t in themes:
        li = "".join(f'<li><a href="{t["slug"]}/{s}/">{e(products[s]["name"])}</a>{open_badge(products[s])}</li>' for s in t["products"])
        rows.append(f'<div class="bgs-contents-group"><h2><a href="{t["slug"]}/">{e(t["title"])}</a></h2><ul>{li}</ul></div>')
    (OUT / "index.md").write_text(f"""---
title: Products
hide:
  - navigation
  - toc
---

<!-- GENERATED by scripts/build_products.py -->

<h1 class="bgs-sr">Product portfolio</h1>
<div class="bgs-cover">
  <div class="bgs-cover-art"><img src="../assets/brand/circle-cover.webp" alt=""></div>
  <div class="bgs-cover-title"><p class="bgs-cover-year">2026–2027</p><p class="bgs-cover-name">Product<br>portfolio</p></div>
</div>

<div class="bgs-contents">
<h2 class="bgs-contents-title">Contents</h2>
<div class="bgs-contents-grid">{''.join(rows)}</div>
</div>
""")

    # splice nav into mkdocs.yml between markers (keeps the rest of the file hand-editable)
    cfg = CONFIG.read_text()
    block = yaml.safe_dump([{"Products": ["products/index.md"] + nav}], sort_keys=False, allow_unicode=True, width=200)
    block = "\n".join("  " + ln for ln in block.rstrip().splitlines())
    cfg = re.sub(r"(# BEGIN GENERATED PRODUCTS NAV\n).*?(\n\s*# END GENERATED PRODUCTS NAV)",
                 lambda m: m.group(1) + block + m.group(2), cfg, flags=re.S)
    CONFIG.write_text(cfg)
    print(f"{len(products)} products, {len(themes)} themes, {len(guides)} hosted guides")


if __name__ == "__main__":
    main()
